- project:
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py36:
            required-projects:
              - openstack/neutron
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py36:
            required-projects:
              - openstack/neutron
    post:
      jobs:
        - publish-openstack-python-branch-tarball
